version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:19.0.1 
    steps:
      - checkout
      - run: npm run lint
  test:
    docker:
    - image: cimg/node:19.0.1 
    steps:
      - checkout
      - run: npm run test
  analyze:
    docker:
    - image: cimg/node:19.0.1 
    steps:
      - checkout
      - run: npm audit

        
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

