version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # - run: npm run lint
      - run: 
          name: linting
          command: npm i; npm run lint
  test:
    docker:
    - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i ; npm run test
  analyze:
    docker:
    - image: cimg/node:13.8.0    
    steps:
      - checkout
      - run: npm;i npm audit

        
workflows:
  build_and_test:
    jobs:
      - build

      - test:
          requires:
            - build
      - analyze:
          requires:
            - test

