version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:9.0.1 
    steps:
      - checkout
      - run:
          name: install-npm
          command: 'sudo npm install -g npm@latest;npm rebuild node-sass;sudo npm install -g --unsafe-perm node-sass '
      # - run:
      #     name: install1
      #     command: npm --add-python-to-path='true' --debug install --global build-tools
      # - run:
      #           name: install-dependencies
      #           command: npm install

      # - run: npm run lint
      - run: 
          name: linting
          command: npm i; npm run lint
  test:
    docker:
    - image: cimg/node:9.0.1 
    steps:
      - checkout
      - run: npm i ; npm install -g jest ; npm run test
  analyze:
    docker:
    - image: cimg/node:9.0.1 
    steps:
      - checkout
      - run: npm;i npm audit

        
workflows:
  build_and_test:
    jobs:
      - build
      - test
      - analyze
      # - test:
      #     requires:
      #       - build

